'use client';
import { useRef, useState } from 'react';
const species=[['🐄','Cow','Bovine social signals'],['🐈','Cat','Feline vocal & body cues'],['🐕','Dog','Canine context patterns'],['🦜','Birds','Avian calls & sequences'],['🐘','Elephant','Infrasound & social contact']];
const bars=[18,28,49,25,60,74,45,29,68,40,81,51,26,59,43,73,31,64,48,80,37,55,28,63,84,40,53,30,69,42,75,35,51,28,64,79,45,32,58,40,70,46,33,61,87,49,24,52,38,73,41,60,30,56,76,43,34,66,50,81,39];
export default function Home(){
 const [selected,setSelected]=useState(4), [message,setMessage]=useState('I am here.'), [uploaded,setUploaded]=useState(''), [saved,setSaved]=useState(false); const input=useRef<HTMLInputElement>(null);
 return <main><aside><div className="brand"><span className="orb">◉</span><div><b>ROR</b><small>RESONANCE · OBSERVATION<br/>· RELATIONSHIP</small></div></div><nav>{[['⌁','Observation'],['◌','Live listening'],['⬡','Species library'],['◷','Communication history'],['▦','Research dataset']].map(([icon,label],i)=><button className={i===0?'active':''} key={label}><i>{icon}</i>{label}</button>)}</nav><div className="side-foot"><span className="dot"/>SYSTEMS NOMINAL<br/><small>Research mode · v0.1</small></div></aside>
 <section className="content"><header><div><p className="eyebrow">FIELD RESEARCH CONSOLE</p><h1>Observe patterns.<br/><em>Respect uncertainty.</em></h1></div><div className="researcher"><span>DR</span><div><b>Researcher workspace</b><small>Local study · private</small></div></div></header>
 <section className="intro panel"><div><p className="eyebrow">ACTIVE PROTOCOL</p><h2>Start a new observation</h2><p>Capture signals with their environment and behaviour—not isolated from context.</p></div><div className="protocol"><span>01</span> CAPTURE <b>→</b><span>02</span> ANALYZE <b>→</b><span>03</span> REVIEW</div></section>
 <div className="grid"><section className="panel species"><div className="section-title"><div><p className="eyebrow">SPECIES LIBRARY</p><h2>Select a subject</h2></div><button className="text-btn">View all →</button></div><div className="species-list">{species.map(([emoji,name,desc],i)=><button className={selected===i?'animal selected':'animal'} onClick={()=>setSelected(i)} key={name}><span>{emoji}</span><div><b>{name}</b><small>{desc}</small></div><i>›</i></button>)}</div></section>
 <section className="panel recording"><div className="section-title"><div><p className="eyebrow">LIVE OBSERVATION</p><h2>Signal capture</h2></div><span className="live"><i/> LIVE READY</span></div><div className="wave">{bars.map((n,i)=><i key={i} style={{height:`${n}%`}}/>)}</div><div className="time"><span>00:00</span><span>00:12</span><span>00:24</span><span>00:36</span><span>00:48</span></div><div className="capture-actions"><button className="primary">◉ Start listening</button><button onClick={()=>input.current?.click()} className="secondary">↥ Upload recording</button><input ref={input} hidden type="file" accept="audio/*" onChange={e=>setUploaded(e.target.files?.[0]?.name || '')}/></div>{uploaded&&<p className="upload">✓ {uploaded} ready for preliminary acoustic analysis</p>}<div className="capture-meta"><span>MICROPHONE <b>CONNECTED</b></span><span>CAMERA <b>OPTIONAL</b></span><span>CONTEXT <b>REQUIRED</b></span></div></section></div>
 <div className="grid lower"><section className="panel interpretation"><p className="eyebrow">INTERPRETATION / E-014</p><div className="tag">POSSIBLE COMMUNICATION PATTERN</div><h2>Social / contact communication</h2><p className="copy">Low-frequency vocalization followed by responses from nearby elephants. This is a research hypothesis, not a verified translation.</p><div className="evidence"><div><b>31</b><span>evidence events</span></div><div><b>74%</b><span>pattern confidence</span></div><div><b>18/31</b><span>response correlation</span></div></div><div className="notice">◈ <span><b>Evidence status: POSSIBLE</b><br/>Repeated observations support further study; cross-individual validation remains pending.</span></div></section>
 <section className="panel response"><p className="eyebrow">HUMAN RESPONSE PANEL</p><h2>Design an experiment</h2><label>What would you like ROR to communicate?</label><textarea value={message} onChange={e=>setMessage(e.target.value)} /><div className="signal-card"><span>EXPERIMENTAL SIGNAL</span><b>18 Hz · 2.4 sec · ×2 repeat</b><small>Playback capped at 62 dB SPL</small></div><div className="response-buttons"><button className="secondary" onClick={()=>setMessage('')}>Cancel</button><button className="primary" onClick={()=>setSaved(true)}>Generate experimental signal</button></div>{saved&&<p className="upload">✓ Experiment drafted. Record the animal response after playback.</p>}</section></div>
 <section className="stats"><div><span>ACTIVE OBSERVATIONS</span><b>128</b><small>+12 this week</small></div><div><span>SIGNAL CLUSTERS</span><b>47</b><small>Across 5 species</small></div><div><span>RESPONSE EVENTS</span><b>386</b><small>Structured records</small></div><div><span>VERIFIED TRANSLATIONS</span><b>0</b><small>Scientific integrity first</small></div></section>
 </section></main>}
